workflows:
  ios-dev:
    name: iOS Dev (TestFlight)
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.pairingplanet.pairingplanetfrontend.dev
      vars:
        FLUTTER_TARGET: lib/main_dev.dart
        PROJECT_PATH: frontend_mobile
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Change to project directory
        script: |
          cd $CM_BUILD_DIR/$PROJECT_PATH
          echo "Working in $(pwd)"
      - name: Get Flutter packages
        script: |
          cd $CM_BUILD_DIR/$PROJECT_PATH
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd $CM_BUILD_DIR/$PROJECT_PATH/ios
          pod install
      - name: Build iOS IPA
        script: |
          cd $CM_BUILD_DIR/$PROJECT_PATH
          flutter build ipa \
            --release \
            --target=$FLUTTER_TARGET \
            --export-options-plist=$HOME/export_options.plist
    artifacts:
      - frontend_mobile/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false

  ios-staging:
    name: iOS Staging (TestFlight)
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.pairingplanet.pairingplanetfrontend.stg
      vars:
        FLUTTER_TARGET: lib/main_staging.dart
        PROJECT_PATH: frontend_mobile
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          cd $CM_BUILD_DIR/$PROJECT_PATH
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd $CM_BUILD_DIR/$PROJECT_PATH/ios
          pod install
      - name: Build iOS IPA
        script: |
          cd $CM_BUILD_DIR/$PROJECT_PATH
          flutter build ipa \
            --release \
            --target=$FLUTTER_TARGET \
            --export-options-plist=$HOME/export_options.plist
    artifacts:
      - frontend_mobile/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false

  ios-production:
    name: iOS Production (App Store)
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.pairingplanet.pairingplanetfrontend.prod
      vars:
        FLUTTER_TARGET: lib/main_prod.dart
        PROJECT_PATH: frontend_mobile
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          cd $CM_BUILD_DIR/$PROJECT_PATH
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd $CM_BUILD_DIR/$PROJECT_PATH/ios
          pod install
      - name: Build iOS IPA
        script: |
          cd $CM_BUILD_DIR/$PROJECT_PATH
          flutter build ipa \
            --release \
            --target=$FLUTTER_TARGET \
            --export-options-plist=$HOME/export_options.plist
    artifacts:
      - frontend_mobile/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
