# Crowdin configuration file
# Documentation: https://crowdin.github.io/crowdin-cli/

project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

# Preserve file hierarchy in Crowdin
preserve_hierarchy: true

files:
  # Frontend Web translations
  - source: /frontend_web/messages/en.json
    translation: /frontend_web/messages/%two_letters_code%.json
