-- Truncate and repopulate autocomplete items
TRUNCATE TABLE autocomplete_items RESTART IDENTITY CASCADE;

-- ==================== DISH NAMES (30) ====================
INSERT INTO autocomplete_items (type, name, score) VALUES
('DISH', '{"en-US": "Kimchi", "ko-KR": "김치", "ja-JP": "キムチ", "fr-FR": "Kimchi", "zh-CN": "泡菜", "es-ES": "Kimchi", "it-IT": "Kimchi"}', 100.0),
('DISH', '{"en-US": "Bibimbap", "ko-KR": "비빔밥", "ja-JP": "ビビンバ", "fr-FR": "Bibimbap", "zh-CN": "拌饭", "es-ES": "Bibimbap", "it-IT": "Bibimbap"}', 98.0),
('DISH', '{"en-US": "Bulgogi", "ko-KR": "불고기", "ja-JP": "プルコギ", "fr-FR": "Bulgogi", "zh-CN": "烤肉", "es-ES": "Bulgogi", "it-IT": "Bulgogi"}', 96.0),
('DISH', '{"en-US": "Japchae", "ko-KR": "잡채", "ja-JP": "チャプチェ", "fr-FR": "Japchae", "zh-CN": "杂菜", "es-ES": "Japchae", "it-IT": "Japchae"}', 94.0),
('DISH', '{"en-US": "Tteokbokki", "ko-KR": "떡볶이", "ja-JP": "トッポッキ", "fr-FR": "Tteokbokki", "zh-CN": "炒年糕", "es-ES": "Tteokbokki", "it-IT": "Tteokbokki"}', 92.0),
('DISH', '{"en-US": "Sushi", "ko-KR": "스시", "ja-JP": "寿司", "fr-FR": "Sushi", "zh-CN": "寿司", "es-ES": "Sushi", "it-IT": "Sushi"}', 100.0),
('DISH', '{"en-US": "Ramen", "ko-KR": "라멘", "ja-JP": "ラーメン", "fr-FR": "Ramen", "zh-CN": "拉面", "es-ES": "Ramen", "it-IT": "Ramen"}', 98.0),
('DISH', '{"en-US": "Tempura", "ko-KR": "덴뿌라", "ja-JP": "天ぷら", "fr-FR": "Tempura", "zh-CN": "天妇罗", "es-ES": "Tempura", "it-IT": "Tempura"}', 94.0),
('DISH', '{"en-US": "Tonkatsu", "ko-KR": "돈카츠", "ja-JP": "とんかつ", "fr-FR": "Tonkatsu", "zh-CN": "炸猪排", "es-ES": "Tonkatsu", "it-IT": "Tonkatsu"}', 92.0),
('DISH', '{"en-US": "Udon", "ko-KR": "우동", "ja-JP": "うどん", "fr-FR": "Udon", "zh-CN": "乌冬面", "es-ES": "Udon", "it-IT": "Udon"}', 90.0),
('DISH', '{"en-US": "Kung Pao Chicken", "ko-KR": "궁보계정", "ja-JP": "宮保鶏丁", "fr-FR": "Poulet Kung Pao", "zh-CN": "宫保鸡丁", "es-ES": "Pollo Kung Pao", "it-IT": "Pollo Kung Pao"}', 96.0),
('DISH', '{"en-US": "Fried Rice", "ko-KR": "볶음밥", "ja-JP": "チャーハン", "fr-FR": "Riz sauté", "zh-CN": "炒饭", "es-ES": "Arroz frito", "it-IT": "Riso fritto"}', 98.0),
('DISH', '{"en-US": "Dumplings", "ko-KR": "만두", "ja-JP": "餃子", "fr-FR": "Raviolis chinois", "zh-CN": "饺子", "es-ES": "Dumplings", "it-IT": "Ravioli cinesi"}', 96.0),
('DISH', '{"en-US": "Mapo Tofu", "ko-KR": "마파두부", "ja-JP": "麻婆豆腐", "fr-FR": "Mapo Tofu", "zh-CN": "麻婆豆腐", "es-ES": "Mapo Tofu", "it-IT": "Mapo Tofu"}', 92.0),
('DISH', '{"en-US": "Pizza", "ko-KR": "피자", "ja-JP": "ピザ", "fr-FR": "Pizza", "zh-CN": "披萨", "es-ES": "Pizza", "it-IT": "Pizza"}', 100.0),
('DISH', '{"en-US": "Spaghetti", "ko-KR": "스파게티", "ja-JP": "スパゲッティ", "fr-FR": "Spaghetti", "zh-CN": "意大利面", "es-ES": "Espagueti", "it-IT": "Spaghetti"}', 98.0),
('DISH', '{"en-US": "Lasagna", "ko-KR": "라자냐", "ja-JP": "ラザニア", "fr-FR": "Lasagnes", "zh-CN": "千层面", "es-ES": "Lasaña", "it-IT": "Lasagna"}', 94.0),
('DISH', '{"en-US": "Risotto", "ko-KR": "리조또", "ja-JP": "リゾット", "fr-FR": "Risotto", "zh-CN": "意大利烩饭", "es-ES": "Risotto", "it-IT": "Risotto"}', 92.0),
('DISH', '{"en-US": "Carbonara", "ko-KR": "까르보나라", "ja-JP": "カルボナーラ", "fr-FR": "Carbonara", "zh-CN": "培根蛋面", "es-ES": "Carbonara", "it-IT": "Carbonara"}', 90.0),
('DISH', '{"en-US": "Croissant", "ko-KR": "크루아상", "ja-JP": "クロワッサン", "fr-FR": "Croissant", "zh-CN": "可颂", "es-ES": "Cruasán", "it-IT": "Croissant"}', 94.0),
('DISH', '{"en-US": "Quiche", "ko-KR": "키쉬", "ja-JP": "キッシュ", "fr-FR": "Quiche", "zh-CN": "法式咸派", "es-ES": "Quiche", "it-IT": "Quiche"}', 88.0),
('DISH', '{"en-US": "Ratatouille", "ko-KR": "라따뚜이", "ja-JP": "ラタトゥイユ", "fr-FR": "Ratatouille", "zh-CN": "普罗旺斯炖菜", "es-ES": "Ratatouille", "it-IT": "Ratatouille"}', 86.0),
('DISH', '{"en-US": "Paella", "ko-KR": "빠에야", "ja-JP": "パエリア", "fr-FR": "Paella", "zh-CN": "西班牙海鲜饭", "es-ES": "Paella", "it-IT": "Paella"}', 96.0),
('DISH', '{"en-US": "Gazpacho", "ko-KR": "가스파초", "ja-JP": "ガスパチョ", "fr-FR": "Gaspacho", "zh-CN": "西班牙冷汤", "es-ES": "Gazpacho", "it-IT": "Gazpacho"}', 84.0),
('DISH', '{"en-US": "Hamburger", "ko-KR": "햄버거", "ja-JP": "ハンバーガー", "fr-FR": "Hamburger", "zh-CN": "汉堡", "es-ES": "Hamburguesa", "it-IT": "Hamburger"}', 100.0),
('DISH', '{"en-US": "Fried Chicken", "ko-KR": "프라이드 치킨", "ja-JP": "フライドチキン", "fr-FR": "Poulet frit", "zh-CN": "炸鸡", "es-ES": "Pollo frito", "it-IT": "Pollo fritto"}', 98.0),
('DISH', '{"en-US": "Taco", "ko-KR": "타코", "ja-JP": "タコス", "fr-FR": "Taco", "zh-CN": "墨西哥卷饼", "es-ES": "Taco", "it-IT": "Taco"}', 94.0),
('DISH', '{"en-US": "Pad Thai", "ko-KR": "팟타이", "ja-JP": "パッタイ", "fr-FR": "Pad Thai", "zh-CN": "泰式炒河粉", "es-ES": "Pad Thai", "it-IT": "Pad Thai"}', 92.0),
('DISH', '{"en-US": "Pho", "ko-KR": "포", "ja-JP": "フォー", "fr-FR": "Pho", "zh-CN": "越南河粉", "es-ES": "Pho", "it-IT": "Pho"}', 90.0),
('DISH', '{"en-US": "Curry", "ko-KR": "카레", "ja-JP": "カレー", "fr-FR": "Curry", "zh-CN": "咖喱", "es-ES": "Curry", "it-IT": "Curry"}', 96.0);

-- ==================== MAIN INGREDIENTS (25) ====================
INSERT INTO autocomplete_items (type, name, score) VALUES
('MAIN_INGREDIENT', '{"en-US": "Chicken", "ko-KR": "닭고기", "ja-JP": "鶏肉", "fr-FR": "Poulet", "zh-CN": "鸡肉", "es-ES": "Pollo", "it-IT": "Pollo"}', 100.0),
('MAIN_INGREDIENT', '{"en-US": "Beef", "ko-KR": "소고기", "ja-JP": "牛肉", "fr-FR": "Boeuf", "zh-CN": "牛肉", "es-ES": "Ternera", "it-IT": "Manzo"}', 98.0),
('MAIN_INGREDIENT', '{"en-US": "Pork", "ko-KR": "돼지고기", "ja-JP": "豚肉", "fr-FR": "Porc", "zh-CN": "猪肉", "es-ES": "Cerdo", "it-IT": "Maiale"}', 96.0),
('MAIN_INGREDIENT', '{"en-US": "Shrimp", "ko-KR": "새우", "ja-JP": "エビ", "fr-FR": "Crevettes", "zh-CN": "虾", "es-ES": "Camarones", "it-IT": "Gamberetti"}', 92.0),
('MAIN_INGREDIENT', '{"en-US": "Salmon", "ko-KR": "연어", "ja-JP": "サーモン", "fr-FR": "Saumon", "zh-CN": "三文鱼", "es-ES": "Salmón", "it-IT": "Salmone"}', 90.0),
('MAIN_INGREDIENT', '{"en-US": "Tuna", "ko-KR": "참치", "ja-JP": "マグロ", "fr-FR": "Thon", "zh-CN": "金枪鱼", "es-ES": "Atún", "it-IT": "Tonno"}', 88.0),
('MAIN_INGREDIENT', '{"en-US": "Tofu", "ko-KR": "두부", "ja-JP": "豆腐", "fr-FR": "Tofu", "zh-CN": "豆腐", "es-ES": "Tofu", "it-IT": "Tofu"}', 94.0),
('MAIN_INGREDIENT', '{"en-US": "Egg", "ko-KR": "계란", "ja-JP": "卵", "fr-FR": "Oeuf", "zh-CN": "鸡蛋", "es-ES": "Huevo", "it-IT": "Uovo"}', 100.0),
('MAIN_INGREDIENT', '{"en-US": "Lamb", "ko-KR": "양고기", "ja-JP": "ラム肉", "fr-FR": "Agneau", "zh-CN": "羊肉", "es-ES": "Cordero", "it-IT": "Agnello"}', 82.0),
('MAIN_INGREDIENT', '{"en-US": "Duck", "ko-KR": "오리고기", "ja-JP": "鴨肉", "fr-FR": "Canard", "zh-CN": "鸭肉", "es-ES": "Pato", "it-IT": "Anatra"}', 80.0),
('MAIN_INGREDIENT', '{"en-US": "Rice", "ko-KR": "쌀", "ja-JP": "米", "fr-FR": "Riz", "zh-CN": "米饭", "es-ES": "Arroz", "it-IT": "Riso"}', 100.0),
('MAIN_INGREDIENT', '{"en-US": "Pasta", "ko-KR": "파스타", "ja-JP": "パスタ", "fr-FR": "Pâtes", "zh-CN": "意大利面", "es-ES": "Pasta", "it-IT": "Pasta"}', 98.0),
('MAIN_INGREDIENT', '{"en-US": "Noodles", "ko-KR": "면", "ja-JP": "麺", "fr-FR": "Nouilles", "zh-CN": "面条", "es-ES": "Fideos", "it-IT": "Noodles"}', 96.0),
('MAIN_INGREDIENT', '{"en-US": "Bread", "ko-KR": "빵", "ja-JP": "パン", "fr-FR": "Pain", "zh-CN": "面包", "es-ES": "Pan", "it-IT": "Pane"}', 94.0),
('MAIN_INGREDIENT', '{"en-US": "Potato", "ko-KR": "감자", "ja-JP": "じゃがいも", "fr-FR": "Pomme de terre", "zh-CN": "土豆", "es-ES": "Patata", "it-IT": "Patata"}', 92.0),
('MAIN_INGREDIENT', '{"en-US": "Cabbage", "ko-KR": "양배추", "ja-JP": "キャベツ", "fr-FR": "Chou", "zh-CN": "卷心菜", "es-ES": "Col", "it-IT": "Cavolo"}', 86.0),
('MAIN_INGREDIENT', '{"en-US": "Spinach", "ko-KR": "시금치", "ja-JP": "ほうれん草", "fr-FR": "Épinards", "zh-CN": "菠菜", "es-ES": "Espinacas", "it-IT": "Spinaci"}', 84.0),
('MAIN_INGREDIENT', '{"en-US": "Eggplant", "ko-KR": "가지", "ja-JP": "ナス", "fr-FR": "Aubergine", "zh-CN": "茄子", "es-ES": "Berenjena", "it-IT": "Melanzana"}', 82.0),
('MAIN_INGREDIENT', '{"en-US": "Zucchini", "ko-KR": "애호박", "ja-JP": "ズッキーニ", "fr-FR": "Courgette", "zh-CN": "西葫芦", "es-ES": "Calabacín", "it-IT": "Zucchina"}', 80.0),
('MAIN_INGREDIENT', '{"en-US": "Mushroom", "ko-KR": "버섯", "ja-JP": "キノコ", "fr-FR": "Champignon", "zh-CN": "蘑菇", "es-ES": "Champiñón", "it-IT": "Fungo"}', 90.0),
('MAIN_INGREDIENT', '{"en-US": "Broccoli", "ko-KR": "브로콜리", "ja-JP": "ブロッコリー", "fr-FR": "Brocoli", "zh-CN": "西兰花", "es-ES": "Brócoli", "it-IT": "Broccoli"}', 88.0),
('MAIN_INGREDIENT', '{"en-US": "Bell Pepper", "ko-KR": "파프리카", "ja-JP": "パプリカ", "fr-FR": "Poivron", "zh-CN": "甜椒", "es-ES": "Pimiento", "it-IT": "Peperone"}', 86.0),
('MAIN_INGREDIENT', '{"en-US": "Crab", "ko-KR": "게", "ja-JP": "カニ", "fr-FR": "Crabe", "zh-CN": "螃蟹", "es-ES": "Cangrejo", "it-IT": "Granchio"}', 78.0),
('MAIN_INGREDIENT', '{"en-US": "Squid", "ko-KR": "오징어", "ja-JP": "イカ", "fr-FR": "Calamar", "zh-CN": "鱿鱼", "es-ES": "Calamar", "it-IT": "Calamaro"}', 76.0),
('MAIN_INGREDIENT', '{"en-US": "Turkey", "ko-KR": "칠면조", "ja-JP": "七面鳥", "fr-FR": "Dinde", "zh-CN": "火鸡", "es-ES": "Pavo", "it-IT": "Tacchino"}', 74.0);

-- ==================== SECONDARY INGREDIENTS (20) ====================
INSERT INTO autocomplete_items (type, name, score) VALUES
('SECONDARY_INGREDIENT', '{"en-US": "Onion", "ko-KR": "양파", "ja-JP": "玉ねぎ", "fr-FR": "Oignon", "zh-CN": "洋葱", "es-ES": "Cebolla", "it-IT": "Cipolla"}', 100.0),
('SECONDARY_INGREDIENT', '{"en-US": "Garlic", "ko-KR": "마늘", "ja-JP": "ニンニク", "fr-FR": "Ail", "zh-CN": "大蒜", "es-ES": "Ajo", "it-IT": "Aglio"}', 100.0),
('SECONDARY_INGREDIENT', '{"en-US": "Ginger", "ko-KR": "생강", "ja-JP": "生姜", "fr-FR": "Gingembre", "zh-CN": "生姜", "es-ES": "Jengibre", "it-IT": "Zenzero"}', 94.0),
('SECONDARY_INGREDIENT', '{"en-US": "Green Onion", "ko-KR": "파", "ja-JP": "ネギ", "fr-FR": "Ciboule", "zh-CN": "葱", "es-ES": "Cebolleta", "it-IT": "Cipollotto"}', 96.0),
('SECONDARY_INGREDIENT', '{"en-US": "Shallot", "ko-KR": "샬롯", "ja-JP": "エシャロット", "fr-FR": "Échalote", "zh-CN": "红葱头", "es-ES": "Chalota", "it-IT": "Scalogno"}', 80.0),
('SECONDARY_INGREDIENT', '{"en-US": "Leek", "ko-KR": "대파", "ja-JP": "リーク", "fr-FR": "Poireau", "zh-CN": "韭葱", "es-ES": "Puerro", "it-IT": "Porro"}', 82.0),
('SECONDARY_INGREDIENT', '{"en-US": "Celery", "ko-KR": "셀러리", "ja-JP": "セロリ", "fr-FR": "Céleri", "zh-CN": "芹菜", "es-ES": "Apio", "it-IT": "Sedano"}', 84.0),
('SECONDARY_INGREDIENT', '{"en-US": "Carrot", "ko-KR": "당근", "ja-JP": "にんじん", "fr-FR": "Carotte", "zh-CN": "胡萝卜", "es-ES": "Zanahoria", "it-IT": "Carota"}', 98.0),
('SECONDARY_INGREDIENT', '{"en-US": "Tomato", "ko-KR": "토마토", "ja-JP": "トマト", "fr-FR": "Tomate", "zh-CN": "番茄", "es-ES": "Tomate", "it-IT": "Pomodoro"}', 98.0),
('SECONDARY_INGREDIENT', '{"en-US": "Cucumber", "ko-KR": "오이", "ja-JP": "きゅうり", "fr-FR": "Concombre", "zh-CN": "黄瓜", "es-ES": "Pepino", "it-IT": "Cetriolo"}', 90.0),
('SECONDARY_INGREDIENT', '{"en-US": "Lettuce", "ko-KR": "상추", "ja-JP": "レタス", "fr-FR": "Laitue", "zh-CN": "生菜", "es-ES": "Lechuga", "it-IT": "Lattuga"}', 88.0),
('SECONDARY_INGREDIENT', '{"en-US": "Bean Sprouts", "ko-KR": "숙주", "ja-JP": "もやし", "fr-FR": "Germes de soja", "zh-CN": "豆芽", "es-ES": "Brotes de soja", "it-IT": "Germogli di soia"}', 82.0),
('SECONDARY_INGREDIENT', '{"en-US": "Corn", "ko-KR": "옥수수", "ja-JP": "とうもろこし", "fr-FR": "Maïs", "zh-CN": "玉米", "es-ES": "Maíz", "it-IT": "Mais"}', 86.0),
('SECONDARY_INGREDIENT', '{"en-US": "Peas", "ko-KR": "완두콩", "ja-JP": "グリーンピース", "fr-FR": "Petits pois", "zh-CN": "豌豆", "es-ES": "Guisantes", "it-IT": "Piselli"}', 80.0),
('SECONDARY_INGREDIENT', '{"en-US": "Cheese", "ko-KR": "치즈", "ja-JP": "チーズ", "fr-FR": "Fromage", "zh-CN": "奶酪", "es-ES": "Queso", "it-IT": "Formaggio"}', 96.0),
('SECONDARY_INGREDIENT', '{"en-US": "Butter", "ko-KR": "버터", "ja-JP": "バター", "fr-FR": "Beurre", "zh-CN": "黄油", "es-ES": "Mantequilla", "it-IT": "Burro"}', 94.0),
('SECONDARY_INGREDIENT', '{"en-US": "Cream", "ko-KR": "크림", "ja-JP": "クリーム", "fr-FR": "Crème", "zh-CN": "奶油", "es-ES": "Nata", "it-IT": "Panna"}', 90.0),
('SECONDARY_INGREDIENT', '{"en-US": "Milk", "ko-KR": "우유", "ja-JP": "牛乳", "fr-FR": "Lait", "zh-CN": "牛奶", "es-ES": "Leche", "it-IT": "Latte"}', 92.0),
('SECONDARY_INGREDIENT', '{"en-US": "Coconut Milk", "ko-KR": "코코넛 밀크", "ja-JP": "ココナッツミルク", "fr-FR": "Lait de coco", "zh-CN": "椰奶", "es-ES": "Leche de coco", "it-IT": "Latte di cocco"}', 78.0),
('SECONDARY_INGREDIENT', '{"en-US": "Radish", "ko-KR": "무", "ja-JP": "大根", "fr-FR": "Radis", "zh-CN": "萝卜", "es-ES": "Rábano", "it-IT": "Ravanello"}', 76.0);

-- ==================== SEASONINGS (30) ====================
INSERT INTO autocomplete_items (type, name, score) VALUES
('SEASONING', '{"en-US": "Soy Sauce", "ko-KR": "간장", "ja-JP": "醤油", "fr-FR": "Sauce soja", "zh-CN": "酱油", "es-ES": "Salsa de soja", "it-IT": "Salsa di soia"}', 100.0),
('SEASONING', '{"en-US": "Fish Sauce", "ko-KR": "액젓", "ja-JP": "ナンプラー", "fr-FR": "Sauce de poisson", "zh-CN": "鱼露", "es-ES": "Salsa de pescado", "it-IT": "Salsa di pesce"}', 88.0),
('SEASONING', '{"en-US": "Oyster Sauce", "ko-KR": "굴소스", "ja-JP": "オイスターソース", "fr-FR": "Sauce d huître", "zh-CN": "蚝油", "es-ES": "Salsa de ostras", "it-IT": "Salsa di ostriche"}', 90.0),
('SEASONING', '{"en-US": "Sesame Oil", "ko-KR": "참기름", "ja-JP": "ごま油", "fr-FR": "Huile de sésame", "zh-CN": "芝麻油", "es-ES": "Aceite de sésamo", "it-IT": "Olio di sesamo"}', 96.0),
('SEASONING', '{"en-US": "Olive Oil", "ko-KR": "올리브유", "ja-JP": "オリーブオイル", "fr-FR": "Huile d olive", "zh-CN": "橄榄油", "es-ES": "Aceite de oliva", "it-IT": "Olio d oliva"}', 98.0),
('SEASONING', '{"en-US": "Vinegar", "ko-KR": "식초", "ja-JP": "酢", "fr-FR": "Vinaigre", "zh-CN": "醋", "es-ES": "Vinagre", "it-IT": "Aceto"}', 92.0),
('SEASONING', '{"en-US": "Hot Sauce", "ko-KR": "핫소스", "ja-JP": "ホットソース", "fr-FR": "Sauce piquante", "zh-CN": "辣椒酱", "es-ES": "Salsa picante", "it-IT": "Salsa piccante"}', 86.0),
('SEASONING', '{"en-US": "Tomato Sauce", "ko-KR": "토마토 소스", "ja-JP": "トマトソース", "fr-FR": "Sauce tomate", "zh-CN": "番茄酱", "es-ES": "Salsa de tomate", "it-IT": "Salsa di pomodoro"}', 94.0),
('SEASONING', '{"en-US": "Gochujang", "ko-KR": "고추장", "ja-JP": "コチュジャン", "fr-FR": "Gochujang", "zh-CN": "辣椒酱", "es-ES": "Gochujang", "it-IT": "Gochujang"}', 92.0),
('SEASONING', '{"en-US": "Miso", "ko-KR": "미소", "ja-JP": "味噌", "fr-FR": "Miso", "zh-CN": "味噌", "es-ES": "Miso", "it-IT": "Miso"}', 88.0),
('SEASONING', '{"en-US": "Salt", "ko-KR": "소금", "ja-JP": "塩", "fr-FR": "Sel", "zh-CN": "盐", "es-ES": "Sal", "it-IT": "Sale"}', 100.0),
('SEASONING', '{"en-US": "Black Pepper", "ko-KR": "후추", "ja-JP": "黒胡椒", "fr-FR": "Poivre noir", "zh-CN": "黑胡椒", "es-ES": "Pimienta negra", "it-IT": "Pepe nero"}', 100.0),
('SEASONING', '{"en-US": "Chili Powder", "ko-KR": "고춧가루", "ja-JP": "唐辛子", "fr-FR": "Piment en poudre", "zh-CN": "辣椒粉", "es-ES": "Chile en polvo", "it-IT": "Peperoncino in polvere"}', 94.0),
('SEASONING', '{"en-US": "Paprika", "ko-KR": "파프리카 가루", "ja-JP": "パプリカ", "fr-FR": "Paprika", "zh-CN": "红椒粉", "es-ES": "Pimentón", "it-IT": "Paprika"}', 86.0),
('SEASONING', '{"en-US": "Cumin", "ko-KR": "큐민", "ja-JP": "クミン", "fr-FR": "Cumin", "zh-CN": "孜然", "es-ES": "Comino", "it-IT": "Cumino"}', 84.0),
('SEASONING', '{"en-US": "Curry Powder", "ko-KR": "카레 가루", "ja-JP": "カレー粉", "fr-FR": "Curry en poudre", "zh-CN": "咖喱粉", "es-ES": "Curry en polvo", "it-IT": "Curry in polvere"}', 90.0),
('SEASONING', '{"en-US": "Cinnamon", "ko-KR": "시나몬", "ja-JP": "シナモン", "fr-FR": "Cannelle", "zh-CN": "肉桂", "es-ES": "Canela", "it-IT": "Cannella"}', 82.0),
('SEASONING', '{"en-US": "Turmeric", "ko-KR": "강황", "ja-JP": "ターメリック", "fr-FR": "Curcuma", "zh-CN": "姜黄", "es-ES": "Cúrcuma", "it-IT": "Curcuma"}', 80.0),
('SEASONING', '{"en-US": "Basil", "ko-KR": "바질", "ja-JP": "バジル", "fr-FR": "Basilic", "zh-CN": "罗勒", "es-ES": "Albahaca", "it-IT": "Basilico"}', 92.0),
('SEASONING', '{"en-US": "Oregano", "ko-KR": "오레가노", "ja-JP": "オレガノ", "fr-FR": "Origan", "zh-CN": "牛至", "es-ES": "Orégano", "it-IT": "Origano"}', 88.0),
('SEASONING', '{"en-US": "Thyme", "ko-KR": "타임", "ja-JP": "タイム", "fr-FR": "Thym", "zh-CN": "百里香", "es-ES": "Tomillo", "it-IT": "Timo"}', 84.0),
('SEASONING', '{"en-US": "Rosemary", "ko-KR": "로즈마리", "ja-JP": "ローズマリー", "fr-FR": "Romarin", "zh-CN": "迷迭香", "es-ES": "Romero", "it-IT": "Rosmarino"}', 82.0),
('SEASONING', '{"en-US": "Parsley", "ko-KR": "파슬리", "ja-JP": "パセリ", "fr-FR": "Persil", "zh-CN": "欧芹", "es-ES": "Perejil", "it-IT": "Prezzemolo"}', 86.0),
('SEASONING', '{"en-US": "Cilantro", "ko-KR": "고수", "ja-JP": "パクチー", "fr-FR": "Coriandre", "zh-CN": "香菜", "es-ES": "Cilantro", "it-IT": "Coriandolo"}', 84.0),
('SEASONING', '{"en-US": "Mint", "ko-KR": "민트", "ja-JP": "ミント", "fr-FR": "Menthe", "zh-CN": "薄荷", "es-ES": "Menta", "it-IT": "Menta"}', 78.0),
('SEASONING', '{"en-US": "Bay Leaf", "ko-KR": "월계수 잎", "ja-JP": "ローリエ", "fr-FR": "Laurier", "zh-CN": "月桂叶", "es-ES": "Laurel", "it-IT": "Alloro"}', 76.0),
('SEASONING', '{"en-US": "Sugar", "ko-KR": "설탕", "ja-JP": "砂糖", "fr-FR": "Sucre", "zh-CN": "糖", "es-ES": "Azúcar", "it-IT": "Zucchero"}', 96.0),
('SEASONING', '{"en-US": "Honey", "ko-KR": "꿀", "ja-JP": "はちみつ", "fr-FR": "Miel", "zh-CN": "蜂蜜", "es-ES": "Miel", "it-IT": "Miele"}', 90.0),
('SEASONING', '{"en-US": "Mayonnaise", "ko-KR": "마요네즈", "ja-JP": "マヨネーズ", "fr-FR": "Mayonnaise", "zh-CN": "蛋黄酱", "es-ES": "Mayonesa", "it-IT": "Maionese"}', 88.0),
('SEASONING', '{"en-US": "Mustard", "ko-KR": "머스타드", "ja-JP": "マスタード", "fr-FR": "Moutarde", "zh-CN": "芥末", "es-ES": "Mostaza", "it-IT": "Senape"}', 84.0);
