// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp9h0yCyeNjBF63g9Ev5iqwfTrdfE9kuo',
    appId: '1:223256199574:web:fb911a77353732cc341db7',
    messagingSenderId: '223256199574',
    projectId: 'pptest-b5da0',
    authDomain: 'pptest-b5da0.firebaseapp.com',
    storageBucket: 'pptest-b5da0.firebasestorage.app',
    measurementId: 'G-0NZC7M4DXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxq9-_u1y3D8oPI1JBpfk5O1a0Otjq-l4',
    appId: '1:223256199574:android:341234bd4c70fa7b341db7',
    messagingSenderId: '223256199574',
    projectId: 'pptest-b5da0',
    storageBucket: 'pptest-b5da0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcGoTEz1wYvRv-xuFATq--zIZTfXnyhCc',
    appId: '1:223256199574:ios:6dea0406ca02c63c341db7',
    messagingSenderId: '223256199574',
    projectId: 'pptest-b5da0',
    storageBucket: 'pptest-b5da0.firebasestorage.app',
    androidClientId: '223256199574-2df9qhloe95tkfup5d5kt7u8qc3bs17m.apps.googleusercontent.com',
    iosClientId: '223256199574-tml2ekiekjqi5e7vb1sj8ragu327k2dg.apps.googleusercontent.com',
    iosBundleId: 'com.pairingplanet.pairingplanetfrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcGoTEz1wYvRv-xuFATq--zIZTfXnyhCc',
    appId: '1:223256199574:ios:827336d6e4982893341db7',
    messagingSenderId: '223256199574',
    projectId: 'pptest-b5da0',
    storageBucket: 'pptest-b5da0.firebasestorage.app',
    androidClientId: '223256199574-2df9qhloe95tkfup5d5kt7u8qc3bs17m.apps.googleusercontent.com',
    iosClientId: '223256199574-02driktqvhf36h99qgv1o8rskbvgiict.apps.googleusercontent.com',
    iosBundleId: 'com.example.pairingPlanet2Frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp9h0yCyeNjBF63g9Ev5iqwfTrdfE9kuo',
    appId: '1:223256199574:web:cc8e50065a932d10341db7',
    messagingSenderId: '223256199574',
    projectId: 'pptest-b5da0',
    authDomain: 'pptest-b5da0.firebaseapp.com',
    storageBucket: 'pptest-b5da0.firebasestorage.app',
    measurementId: 'G-FPMTCZG24G',
  );
}
