name: Cookstemma
options:
  bundleIdPrefix: com.cookstemma
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.2"
  createIntermediateGroups: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"

packages:
  firebase-ios-sdk:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: "11.0.0"
  GoogleSignIn-iOS:
    url: https://github.com/google/GoogleSignIn-iOS.git
    from: "8.0.0"

targets:
  Cookstemma:
    type: application
    platform: iOS
    sources:
      - path: App
      - path: Data
      - path: Domain
      - path: Presentation
      - path: Resources
    dependencies:
      - package: firebase-ios-sdk
        product: FirebaseAuth
      - package: GoogleSignIn-iOS
        product: GoogleSignIn
      - package: GoogleSignIn-iOS
        product: GoogleSignInSwift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cookstemma.app
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: DFAR672Q54
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: false
    entitlements:
      path: Resources/Cookstemma.entitlements
      properties:
        com.apple.developer.applesignin:
          - Default
    info:
      path: Resources/Info.plist
      properties:
        CFBundleDisplayName: Cookstemma
        CFBundleName: $(PRODUCT_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
            CFBundleURLSchemes:
              - com.googleusercontent.apps.946572066572-bng1tcf3i8r0g06orikdpnoh0ar5k1u9

  CookstemmaTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
        excludes:
          - "UITests/**"
    dependencies:
      - target: Cookstemma
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cookstemma.tests
        INFOPLIST_FILE: Tests/Info.plist
        GENERATE_INFOPLIST_FILE: true

  CookstemmaUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: UITests
    dependencies:
      - target: Cookstemma
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cookstemma.uitests
        INFOPLIST_FILE: UITests/Info.plist
        GENERATE_INFOPLIST_FILE: true

schemes:
  Cookstemma:
    build:
      targets:
        Cookstemma: all
        CookstemmaTests: [test]
        CookstemmaUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - CookstemmaTests
        - CookstemmaUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
